In [1]:
import pandas


In [2]:
dataset=pandas.read_csv("xyzcollege - Sheet1.csv")

In [3]:
dataset


name  hrs  marks
0  harry    2     20
1   eric    5     50
2    tom    7     70
3   yash    3     30

In [4]:
#extracting a column
y=dataset["marks"]

In [8]:
x=dataset["hrs"]

In [5]:
y

0    20
1    50
2    70
3    30
Name: marks, dtype: int64

In [6]:
#Linear Regression 
from sklearn.linear_model import LinearRegression

In [7]:
model=LinearRegression()

In [17]:
model.fit(X,y)

LinearRegression()

In [14]:
X=x.to_numpy()

In [16]:
X=X.reshape(-1,1)

In [19]:
X.shape

(4, 1)

In [20]:
X.ndim

2

In [21]:
model.predict([[5]])

array([50.])

In [22]:
model.coef_

array([10.])

In [23]:
import joblib

In [24]:
joblib.dump(model,"mymarkspredict.model")

['mymarkspredict.model']

In [25]:
mind =joblib.load("mymarkspredict.model")

In [26]:
mind.predict([[9]])

array([90.])