In [ ]:
#pip install pandas

In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("student.csv",header=None)

In [3]:
dataset


0      1   2  3
0  1   aman  30  3
1  2  rahul  40  4
2  3    zen  20  2

In [4]:
dataset.columns=["RollNo","Name","Marks","hrs"]

In [5]:
dataset

RollNo   Name  Marks  hrs
0       1   aman     30    3
1       2  rahul     40    4
2       3    zen     20    2

In [6]:
#dependent variable
y=dataset['Marks']

In [12]:
y

0    30
1    40
2    20
Name: Marks, dtype: int64

In [7]:
#independent variable
x=dataset['hrs']

In [13]:
x

0    3
1    4
2    2
Name: hrs, dtype: int64

In [8]:
#pip install numpy

In [9]:
from numpy import array

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model=LinearRegression()

In [14]:
model.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[3 4 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [15]:
new_x=x.values

In [16]:
new_x.shape

(3,)

In [17]:
X=new_x.reshape(3,1)

In [18]:
X

array([[3],
       [4],
       [2]], dtype=int64)

In [19]:
model.fit(X,y)

LinearRegression()

In [22]:
model.predict ( [ [24] ] )

array([240.])

In [23]:
model.coef_

array([10.])

In [24]:
model.intercept_

7.105427357601002e-15

In [25]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [26]:
import joblib

In [27]:
joblib.dump(model,"predictmarks.model")

['predictmarks.model']